# ===== report-service =====
spring.application.name=report-service
server.port=8088




# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
service.auth.url=http://localhost:8081
# Actuator
management.endpoints.web.exposure.include=health,info
service.product.url=http://localhost:8082
service.warehouse.url=http://localhost:8083

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true